<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Daily Entries Report</title>
    <style>
        @page {
            margin: 25px 30px;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            color: #1e293b;
            line-height: 1.4;
        }
        .header-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            border-bottom: 2px solid #4f46e5;
            padding-bottom: 8px;
        }
        .company-title {
            font-size: 18px;
            font-weight: bold;
            color: #4f46e5;
            text-transform: uppercase;
        }
        .report-title {
            font-size: 14px;
            font-weight: bold;
            color: #0f172a;
            text-align: right;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .table th {
            background-color: #4f46e5;
            color: #ffffff;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 8.5px;
            padding: 6px 8px;
            border: 1px solid #4f46e5;
            text-align: left;
        }
        .table td {
            padding: 5px 8px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 9px;
            text-align: left;
        }
        .table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .text-left { text-align: left !important; }
        .text-right { text-align: right !important; }
        .text-center { text-align: center !important; }
        .fw-bold { font-weight: bold; }
        .text-success { color: #16a34a; }
        .text-danger { color: #dc2626; }
        .text-muted { color: #64748b; }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8.5px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 6px;
        }
    </style>
</head>
<body>
    <table class="header-table">
        <tr>
            <td>
                <div class="company-title">{{ auth()->user()->client->name ?? config('app.name', 'Hisab Ledger') }}</div>
                <div class="text-muted" style="font-size: 9px;">Daily Counter Sales & Entries Report</div>
            </td>
            <td class="report-title">
                DAILY ENTRIES STATEMENT
                <div class="text-muted" style="font-size: 9px; font-weight: normal;">Generated on: {{ now()->format('d M Y, h:i A') }}</div>
            </td>
        </tr>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th style="width: 12%; text-align: left;">Date</th>
                <th style="width: 22%; text-align: left;">Customer Name</th>
                <th style="width: 28%; text-align: left;">Description</th>
                <th style="width: 12%; text-align: left;">Mode</th>
                <th style="width: 13%; text-align: right;">Total Amt</th>
                <th style="width: 13%; text-align: right;">Paid Amt</th>
            </tr>
        </thead>
        <tbody>
            @forelse($exportEntries as $entry)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($entry->entry_date)->format('d M Y') }}</td>
                    <td>
                        <div class="fw-bold">{{ $entry->customer_name }}</div>
                        @if($entry->mobile_number)
                            <div class="text-muted" style="font-size: 8px;">{{ $entry->mobile_number }}</div>
                        @endif
                    </td>
                    <td>{{ $entry->description }}</td>
                    <td>{{ $entry->payment_mode ?? 'CASH' }}</td>
                    <td class="text-right fw-bold">Rs. {{ number_format($entry->total_amount, 2) }}</td>
                    <td class="text-right fw-bold text-success">Rs. {{ number_format($entry->paid_amount, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center text-muted" style="padding: 15px;">No daily entries found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Total Entries Listed: {{ count($exportEntries) }} | Generated by {{ config('app.name', 'Hisab Ledger') }}
    </div>
</body>
</html>
