<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        \Illuminate\Pagination\Paginator::useBootstrapFive();

        // Automatic Slow Query Monitoring
        \Illuminate\Support\Facades\DB::listen(function ($query) {
            // Ignore queries generated by the logging mechanism itself to prevent infinite loops
            if (str_contains($query->sql, 'slow_query_logs') || str_contains($query->sql, 'slow_query_settings')) {
                return;
            }

            try {
                // Static cache threshold to prevent DB query inside listener
                static $threshold = null;
                if ($threshold === null) {
                    $setting = \Illuminate\Support\Facades\DB::table('slow_query_settings')->where('id', 1)->first();
                    $threshold = $setting ? $setting->threshold_ms : 500;
                }

                if ($query->time >= $threshold) {
                    $userId = auth()->id();
                    $clientId = auth()->user()->client_id ?? null;

                    \Illuminate\Support\Facades\DB::table('slow_query_logs')->insert([
                        'query_text' => $query->sql,
                        'query_type' => strtoupper(strtok($query->sql, ' ')),
                        'duration_ms' => (int) round($query->time),
                        'threshold_ms' => $threshold,
                        'endpoint' => request()->path(),
                        'http_method' => request()->method(),
                        'user_id' => $userId,
                        'client_id' => $clientId,
                        'executed_at' => now(),
                    ]);
                }
            } catch (\Throwable $e) {
                // Prevent query logger from interrupting normal application execution
            }
        });
    }
}
